packages:
  - apps/*
  - packages/*
  - tooling/*
  - assets/packaged/*
  - docs

catalog:
  "@tanstack/react-query": ^5.59.15
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
  eslint: ^9.12.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.14
  typescript: ^5.6.3
  zod: ^3.23.8
  next: ^14.2.3
  "@vitest/ui": ^2.1.8
  vitest: "2.1.8"
  # There's a bug with the latest version as of 01.25
  # @see https://github.com/vercel/vercel/issues/11097
  vercel: "33.2.0"
  "@playwright/test": ^1.40.1
  "jiti": "^2.3.3"

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
