name: Vercel Preview Deployment

description: Deploy to Vercel and set the preview URL

inputs:
  project_name:
    description: "The working directory/project name you're trying to deploy. Example: 'www', 'blog'"
    required: true
  VERCEL_TOKEN:
    description: "Vercel token for authentication"
    required: true
  VERCEL_ORG_ID:
    description: "Vercel organization ID"
    required: true
  VERCEL_PROJECT_ID:
    description: "Vercel project ID"
    required: true
  GITHUB_TOKEN:
    description: "GH token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Deploy to Vercel Preview
      shell: bash
      env: VERCEL_TOKEN=${{ inputs.VERCEL_TOKEN }}
        VERCEL_ORG_ID=${{ inputs.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID=${{ inputs.VERCEL_PROJECT_ID }}
      run: |
        cd ${{ inputs.project_name }} && \
        PREVIEW_URL=$(pnpm --filter @ashgw/${{ inputs.project_name }} deploy:vercel-preview --token=${{ inputs.VERCEL_TOKEN }}) && \
        echo "PREVIEW_URL=$PREVIEW_URL" >> $GITHUB_ENV
    - name: Comment Preview URL
      uses: actions/github-script@v6
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        PROJECT_NAME: ${{ inputs.project_name }}
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Deployed 🚀 ${process.env.PROJECT_NAME}. Preview is ready at: ${process.env.PREVIEW_URL}`
          })
